[package]
name = "rust-qr-code-generator"
version = "0.1.0"
authors = ["Alexander Craggs <github@femto.host>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
qrcode-generator = "4.1.1"